### PR TITLE
feat(privatevpn): support natively port forwarding

### PR DESCRIPTION
**Pull request by qdm12**
Try with `docker run -it --rm --cap-add=NET_ADMIN -e OPENVPN_USER=a -e OPENVPN_PASSWORD=b -e VPN_SERVICE_PROVIDER=privatevpn -e VPN_PORT_FORWARDING=on qmcgaw/gluetun:pr-2285`

For issue #1859 

- [x] Implemenation done
- [x] User feedback
- [x] Wiki updated

### CODE REVIEW

**Comment by teopost** [comment]
Hi,
   I tried running the image qmcgaw/gluetun:pr-2285.
I'm getting this error:

```
2024-08-11T20:10:14Z ERROR [vpn] getting VPN assigned IP address: network interface tun0 not found: route ip+net: no such network interface
```

this is the ful log 

```
2024-08-11T20:09:49Z INFO [routing] default route found: interface eth0, gateway 172.22.0.1, assigned IP 172.22.0.4 and family v4
2024-08-11T20:09:49Z INFO [routing] adding route for 0.0.0.0/0
2024-08-11T20:09:49Z INFO [firewall] setting allowed subnets...
2024-08-11T20:09:49Z INFO [routing] default route found: interface eth0, gateway 172.22.0.1, assigned IP 172.22.0.4 and family v4
2024-08-11T20:09:49Z INFO [dns] using plaintext DNS at address 1.1.1.1
2024-08-11T20:09:49Z INFO [http proxy] listening on :8888
2024-08-11T20:09:49Z INFO [http server] http server listening on [::]:8000
2024-08-11T20:09:49Z INFO [firewall] allowing VPN connection...
2024-08-11T20:09:49Z INFO [healthcheck] listening on 127.0.0.1:9999
2024-08-11T20:09:49Z INFO [openvpn] OpenVPN 2.6.11 aarch64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD]
2024-08-11T20:09:49Z INFO [openvpn] library versions: OpenSSL 3.3.1 4 Jun 2024, LZO 2.10
2024-08-11T20:09:49Z INFO [openvpn] TCP/UDP: Preserving recently used remote address: [AF_INET]193.180.119.196:1194
2024-08-11T20:09:49Z INFO [openvpn] UDPv4 link local: (not bound)
2024-08-11T20:09:49Z INFO [openvpn] UDPv4 link remote: [AF_INET]193.180.119.196:1194
2024-08-11T20:09:49Z INFO [openvpn] [PrivateVPN] Peer Connection Initiated with [AF_INET]193.180.119.196:1194
2024-08-11T20:09:50Z INFO [openvpn] TUN/TAP device tun0 opened
2024-08-11T20:09:50Z INFO [openvpn] /sbin/ip link set dev tun0 up mtu 1500
2024-08-11T20:09:51Z INFO [openvpn] /sbin/ip link set dev tun0 up
2024-08-11T20:09:51Z INFO [openvpn] /sbin/ip addr add dev tun0 10.35.14.63/23
2024-08-11T20:09:51Z INFO [openvpn] UID set to nonrootuser
2024-08-11T20:09:51Z INFO [openvpn] Initialization Sequence Completed
2024-08-11T20:09:51Z INFO [dns] downloading DNS over TLS cryptographic files
2024-08-11T20:09:51Z INFO [healthcheck] healthy!
2024-08-11T20:09:52Z INFO [dns] downloading hostnames and IP block lists
2024-08-11T20:10:14Z INFO [healthcheck] program has been unhealthy for 6s: restarting VPN
2024-08-11T20:10:14Z INFO [healthcheck] 👉 See https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md
2024-08-11T20:10:14Z INFO [healthcheck] DO NOT OPEN AN ISSUE UNLESS YOU READ AND TRIED EACH POSSIBLE SOLUTION
2024-08-11T20:10:14Z INFO [vpn] stopping
2024-08-11T20:10:14Z ERROR [vpn] getting public IP address information: fetching information: Get "https://ipinfo.io/": context canceled
2024-08-11T20:10:14Z ERROR [vpn] cannot get version information: Get "https://api.github.com/repos/qdm12/gluetun/releases": context canceled
2024-08-11T20:10:14Z INFO [port forwarding] starting
2024-08-11T20:10:14Z ERROR [vpn] getting VPN assigned IP address: network interface tun0 not found: route ip+net: no such network interface
2024-08-11T20:10:14Z INFO [vpn] starting
2024-08-11T20:10:14Z INFO [firewall] allowing VPN connection...
2024-08-11T20:10:15Z INFO [openvpn] OpenVPN 2.6.11 aarch64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD]
2024-08-11T20:10:15Z INFO [openvpn] library versions: OpenSSL 3.3.1 4 Jun 2024, LZO 2.10
2024-08-11T20:10:15Z INFO [openvpn] TCP/UDP: Preserving recently used remote address: [AF_INET]193.180.119.196:1194
2024-08-11T20:10:15Z INFO [openvpn] UDPv4 link local: (not bound)
2024-08-11T20:10:15Z INFO [openvpn] UDPv4 link remote: [AF_INET]193.180.119.196:1194
2024-08-11T20:10:15Z INFO [openvpn] [PrivateVPN] Peer Connection Initiated with [AF_INET]193.180.119.196:1194
2024-08-11T20:10:16Z INFO [openvpn] TUN/TAP device tun0 opened
2024-08-11T20:10:16Z INFO [openvpn] /sbin/ip link set dev tun0 up mtu 1500
2024-08-11T20:10:16Z INFO [openvpn] /sbin/ip link set dev tun0 up
2024-08-11T20:10:16Z INFO [openvpn] /sbin/ip addr add dev tun0 10.35.14.69/23
2024-08-11T20:10:16Z ERROR [openvpn] OpenVPN tried to add an IP route which already exists (RTNETLINK answers: File exists)
2024-08-11T20:10:16Z WARN [openvpn] Previous error details: Linux route add command failed: external program exited with error status: 2
2024-08-11T20:10:16Z ERROR [openvpn] Linux route add command failed
2024-08-11T20:10:16Z INFO [openvpn] UID set to nonrootuser
2024-08-11T20:10:16Z INFO [openvpn] Initialization Sequence Completed
2024-08-11T20:10:25Z INFO [dns] init module 0: validator
2024-08-11T20:10:25Z INFO [dns] init module 1: iterator
2024-08-11T20:10:25Z INFO [dns] start of service (unbound 1.20.0).
2024-08-11T20:10:25Z INFO [dns] generate keytag query _ta-4a5c-4f66-9728. NULL IN
2024-08-11T20:10:25Z INFO [dns] generate keytag query _ta-4a5c-4f66-9728. NULL IN
2024-08-11T20:10:26Z INFO [healthcheck] healthy!
2024-08-11T20:10:26Z INFO [ip getter] Public IP address is 80.239.140.196 (Netherlands, North Holland, Amsterdam)
2024-08-11T20:10:26Z INFO [port forwarding] starting
2024-08-11T20:10:26Z ERROR [vpn] port forwarding for the first time: custom port forwarding obtention is not supported: for privatevpn
2024-08-11T20:10:26Z INFO [dns] ready
```

and this is a portion of my compose file

```
services:
  gluetun:
    image: qmcgaw/gluetun:pr-2285
#    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8091:8000/tcp 
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - "0.0.0.0:9091:9091/tcp"  # transmission
      - 51413:51413/tcp          # transmission
      - 51413:51413/udp          # transmission
    volumes:
      - ./configs/gluetun-config:/gluetun
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - HTTPPROXY=on
      - VPN_SERVICE_PROVIDER=privatevpn
      - VPN_PORT_FORWARDING=on
      - OPENVPN_USER=<username>
      - OPENVPN_PASSWORD=<password>
      - SERVER_COUNTRIES=Netherlands

    restart: unless-stopped
    networks:
      - internal

```

**Comment by qdm12** [comment]
Fixed! Please try pulling the image 😉 

`ERROR [vpn] getting VPN assigned IP address: network interface tun0 not found` was due to just the VPN being torn down due to being unhealthy (`vpn] stopping`). The real error that got fixed was `ERROR [vpn] port forwarding for the first time: custom port forwarding obtention is not supported: for privatevpn`. This was a simple bug due to me updating this branch on top of the master branch where code was changed to support multiple forwarded ports, but the privatevpn was still on the single-port support, so that was the mismatch fixed in https://github.com/qdm12/gluetun/pull/2285/commits/5d3526c88d854c1050066572365b195e7d405125

**Comment by varac** [comment]
Should this also work for wireguard ?
I'm getting 

```
...
INFO [port forwarding] starting
ERROR [vpn] starting port forwarding service: port forwarding for the first time: port forwarding not supported for this VPN server     
```

**Comment by pzmarzly** [comment]
@varac I confirm port forwarding doesn't work for any Wireguard server. I'll add this information to PrivateVPN documentation in https://github.com/qdm12/gluetun-wiki/pull/134

**Pull request merged**
