### PR TITLE
Feature request: Support new PIA servers #216

### PR DESCRIPTION
**Pull request by hyness**
- Change domain to privacy.network

### CODE REVIEW

**Comment by hyness** [comment]
Before I submitted the pull request, I built a test image for Switzerland and it works.  The `forwarded-port` file is being created.  I diffed the two configs before attempting to build, and this was the only difference I saw.

Here are some more diffs
```
$ diff pia-legacy/US\ California.ovpn pia-nextgen/US\ California.ovpn 
4c4
< remote us-california.privateinternetaccess.com 1198
---
> remote us-california.privacy.network 1198

$ diff pia-legacy/US\ Silicon\ Valley.ovpn pia-nextgen/US\ Silicon\ Valley.ovpn 
4c4
< remote us-siliconvalley.privateinternetaccess.com 1198
---
> remote us-siliconvalley.privacy.network 1198

$ diff pia-legacy/DE\ Berlin.ovpn  pia-nextgen/DE\ Berlin.ovpn 
4c4
< remote de-berlin.privateinternetaccess.com 1198
---
> remote de-berlin.privacy.network 1198

$ diff pia-legacy/Netherlands.ovpn  pia-nextgen/Netherlands.ovpn 
4c4
< remote nl.privateinternetaccess.com 1198
---
> remote nl-amsterdam.privacy.network 1198

```

**Comment by hyness** [comment]
I've updated the subdomains.  A few regions aren't in nextgen (CA Vancouver ,UK Southampton, US Dallas, East, Las Vegas, New York City) so I removed them.  Also, I see this error in the logs, but it's not stopping the container from starting or connecting to PIA
```
ERROR	openvpn: Get "http://209.222.18.222:2000/?client_id=a63fb00ce9a0cb7fcde80f190461728e2a9cadb3a71fed4c096f22815eae5964": dial tcp 209.222.18.222:2000: connect: connection refused
```

**Comment by qdm12** [comment]
Hm actually that error is important and is for port forwarding, quite a few users seem to use it. although it never worked for me but that's another story.

Maybe I can add an env variable to use the newer pia servers so existing users can keep using the old servers.

**Comment by hyness** [comment]
@qdm12  Sorry for the muddled comments.  Port forwarding does work, it's the reason I edited your image so I could restore it.  Not every region supports port forwarding, and that error came from a region that doesn't support it  Switzerland doesn't have that error, a region that allows port forwarding

**Comment by qdm12** [comment]
Ah ok great! Although the file you changed is a tool to obtain the IP addresses which are hardcoded in internal/constants/pia.go. That's fine though, I can do it myself relatively easily.

Sorry about that but I forced-push the [last commit](https://github.com/qdm12/gluetun/commit/15ddbdefef48e71eb3bab947b7a62134d2250d79), could you perhaps rebase your fork on it or re-do the fork? Alternatively I can use your changes directly, but I guess you would want to be part of the contributors on Github 👍 🥇

**Comment by hyness** [comment]
Ok, I've rebased and force pushed my frork

**Comment by qdm12** [comment]
Great thanks! One last thing - sorry to be annoying - would you mind having the new pia servers in another function like

```go
func piaNewServers() []server {
	return []server{
		{subdomain: "au-melbourne", region: "AU Melbourne"},
	}
}
```

To keep the old servers still there until the transition is done? I'll then finally merge it. Thanks!

**Comment by hyness** [comment]
As requested., I've created a new function called `piaNextgenServers`, restored the old servers and force pushed that as a single commit.  I tried to figure out how it's referenced, but this is the first time writing any golang.  Need some sort of flag for nextgen and then switch out the servers and subdomain.  Hopefully this is helpful

**Comment by qdm12** [comment]
It's not directly used for now, this is some tooling to help me re-resolve the domain names. It is definitely useful though. I'll continue the work and ping you for pull request reviews, it's a good way to learn I guess :wink: You might also want to use that development container with vscode, it definitely helps getting setup (see the wiki).

**Comment by qdm12** [comment]
Hey there, I finished a [pull request for newer PIA servers](https://github.com/qdm12/gluetun/pull/227). Feel free to review / comment on it 😉 

Also if you could try with the Docker image tag `:new-pia-servers` and see if it works for you? Thanks!

**Pull request merged**
