### PR TITLE
Update for Windscribe config

### PR DESCRIPTION
**Pull request by TJJP**
Here is a message from the Windscribe website: OpenVPN compression phaseout is in progress and will be completed by August 3rd 2021.
If you downloaded configs from this page before you saw this message, you need to re-download them now, or simply remove the compress or comp-lzo flags from the config that you downloaded after July 20th 2021.

I think this should fix gluetun from not being able to connect.

### CODE REVIEW

**Comment by harrv** [comment]
Thank you TJJP! I think I need this. Windscribe no longer works for me with gluetun. Please merge!

Here is the windscribe blog post about needing new configs and that the old ones would stop working today! Apparently that happened. Thanks. https://blog.windscribe.com/openvpn-security-improvements-and-changes-7b04ea49222

**Comment by nicopasla** [comment]
So that's why it's not working, thanks!

**Comment by qdm12** [comment]
@TJJP Thanks! There is however one more thing missing which may be a bit complicated, to add `verify-x509-name` with the hostname (or subdomain/host?). Have you tried the image? You can easily (and fast) build it with `docker build -t qmcgaw/gluetun .`.

If TLS validation fails, either:

- work your way by modifying Windscribe's connection.go to bundle in the server hostname (already in the server structure) inside the connection model, then add that `verify-x509-name` to the openvpnconf.go. Also update a comment on the `Hostname` field in the connection model saying it's used for Privado and Windscribe only
- Or merge your PR in branch `windscribe-2021-07-20` and I can take care of the rest.

**Comment by TJJP** [comment]
@qdm12 Yes, I have tried the image and I believe it is working because it gave me a new IP address. No errors that I can remember.

**Comment by qdm12** [comment]
I merged it thanks @TJJP

If you don't mind I'll soon give you an image to test out with that tls verification I was talking about, I'll comment with a Docker tag to try here.

**Comment by TJJP** [comment]
I do not mind, happy to test it out!

**Comment by qdm12** [comment]
1. @TJJP I'm wondering, is each CA certificate now unique to a server?

    I can see from their blog:

    > This was previously impossible because the server certificates were generic and did not contain metadata unique to each server/location.

2. Do any of you have an example of new openvpn config? I'm curious how exactly their `verify-x509-name` line looks like

**Comment by qdm12** [comment]
I also have an image with tag `:windscribe-verify-x509-name` if someone can try it out 😉 

It uses `"verify-x509-name " + connection.Hostname + " name"`, not sure if this is the right format they expect in their config but it might be.

Thanks!

**Comment by harrv** [comment]
I can verify that the new docker image built a few hours ago worked for me once I deleted the already-existing servers.json file.

I did manually download a new config yesterday, for a specific server, and the verify-x509-name line looks like this:

`verify-x509-name lax-310.windscribe.com name`

**Comment by harrv** [comment]
I tried the image with the `:windscribe-verify-x509-name` tag and it gets failures. There is this section at the end of the logs.

```gluetun           | 2021/07/21 16:57:55 INFO healthcheck: program has been unhealthy for 11s: restarting OpenVPN
gluetun           | 2021/07/21 16:57:59 INFO firewall: setting VPN connection through firewall...
gluetun           | 2021/07/21 16:57:59 INFO openvpn configurator: starting OpenVPN 2.5
gluetun           | 2021/07/21 16:57:59 INFO openvpn: 2021-07-21 16:57:59 DEPRECATED OPTION: ncp-disable. Disabling cipher negotiation is a deprecated debug feature that will be removed in OpenVPN 2.6
gluetun           | 2021/07/21 16:57:59 INFO openvpn: OpenVPN 2.5.2 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  4 2021
gluetun           | 2021/07/21 16:57:59 INFO openvpn: library versions: OpenSSL 1.1.1k  25 Mar 2021, LZO 2.10
gluetun           | 2021/07/21 16:57:59 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]82.102.30.67:443
gluetun           | 2021/07/21 16:57:59 INFO openvpn: UDP link local: (not bound)
gluetun           | 2021/07/21 16:57:59 INFO openvpn: UDP link remote: [AF_INET]82.102.30.67:443
gluetun           | 2021/07/21 16:57:59 INFO openvpn: OpenSSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
gluetun           | 2021/07/21 16:57:59 INFO openvpn: TLS_ERROR: BIO read tls_read_plaintext error
gluetun           | 2021/07/21 16:57:59 INFO openvpn: TLS Error: TLS object -> incoming plaintext read error
gluetun           | 2021/07/21 16:57:59 INFO openvpn: TLS Error: TLS handshake failed
gluetun           | 2021/07/21 16:57:59 INFO openvpn: SIGTERM[soft,tls-error] received, process exiting
```

**Comment by TJJP** [comment]
@qdm12 I asked and this is what they said: 
image
So, the CA is not unique and it looks like it is the right format, but it is also failing for me.

**Comment by qdm12** [comment]
> So, the CA is not unique and it looks like it is the right format, but it is also failing for me.

Nice perfect!

My mistake was I was using the VPN server hostname (something.whiskergalaxy.com). I am now using the x509 name downloaded from their API, so it should now work. Feel free to re-pull and try if it works.

**Comment by TJJP** [comment]
That worked for me, but I keep getting this error and it takes a while to bring up the project: 

```
2021/07/22 03:00:59 INFO storage: merging by most recent 11213 hardcoded servers and 11213 servers read from /gluetun/servers.json
2021/07/22 03:00:59 INFO routing: default route found: interface eth0, gateway 172.17.0.1
2021/07/22 03:00:59 INFO routing: local ethernet link found: eth0
2021/07/22 03:00:59 INFO routing: local ipnet found: 172.17.0.0/16
2021/07/22 03:00:59 INFO routing: default route found: interface eth0, gateway 172.17.0.1
2021/07/22 03:00:59 INFO routing: adding route for 0.0.0.0/0
2021/07/22 03:00:59 INFO firewall: firewall disabled, only updating allowed subnets internal list
2021/07/22 03:00:59 INFO routing: default route found: interface eth0, gateway 172.17.0.1
2021/07/22 03:00:59 INFO openvpn configurator: checking for device /dev/net/tun
2021/07/22 03:00:59 WARN TUN device is not available: open /dev/net/tun: no such file or directory
2021/07/22 03:00:59 INFO openvpn configurator: creating /dev/net/tun
2021/07/22 03:00:59 INFO firewall: enabling...
2021/07/22 03:01:00 INFO firewall: enabled successfully
2021/07/22 03:01:00 DEBUG healthcheck: here 0
2021/07/22 03:01:00 INFO healthcheck: listening on 127.0.0.1:9999
2021/07/22 03:01:00 INFO dns over tls: using plaintext DNS at address 1.1.1.1
2021/07/22 03:01:00 INFO http server: listening on :8000
2021/07/22 03:01:00 INFO firewall: setting VPN connection through firewall...
2021/07/22 03:01:00 INFO openvpn configurator: starting OpenVPN 2.5
2021/07/22 03:01:00 INFO openvpn: 2021-07-22 03:01:00 DEPRECATED OPTION: ncp-disable. Disabling cipher negotiation is a deprecated debug feature that will be removed in OpenVPN 2.6
2021/07/22 03:01:00 INFO openvpn: OpenVPN 2.5.2 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  4 2021
2021/07/22 03:01:00 INFO openvpn: library versions: OpenSSL 1.1.1k  25 Mar 2021, LZO 2.10
2021/07/22 03:01:00 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]103.205.140.177:443
2021/07/22 03:01:00 INFO openvpn: UDP link local: (not bound)
2021/07/22 03:01:00 INFO openvpn: UDP link remote: [AF_INET]103.205.140.177:443
2021/07/22 03:01:06 INFO healthcheck: program has been unhealthy for 6s: restarting OpenVPN
2021/07/22 03:01:06 INFO openvpn: stopping
2021/07/22 03:01:06 INFO openvpn: starting
2021/07/22 03:01:06 INFO firewall: setting VPN connection through firewall...
2021/07/22 03:01:06 INFO openvpn configurator: starting OpenVPN 2.5
2021/07/22 03:01:06 INFO openvpn: 2021-07-22 03:01:06 DEPRECATED OPTION: ncp-disable. Disabling cipher negotiation is a deprecated debug feature that will be removed in OpenVPN 2.6
2021/07/22 03:01:06 INFO openvpn: OpenVPN 2.5.2 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  4 2021
2021/07/22 03:01:06 INFO openvpn: library versions: OpenSSL 1.1.1k  25 Mar 2021, LZO 2.10
2021/07/22 03:01:06 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]116.206.228.68:443
2021/07/22 03:01:06 INFO openvpn: UDP link local: (not bound)
2021/07/22 03:01:06 INFO openvpn: UDP link remote: [AF_INET]116.206.228.68:443
2021/07/22 03:01:17 INFO healthcheck: program has been unhealthy for 11s: restarting OpenVPN
2021/07/22 03:01:17 INFO openvpn: stopping
2021/07/22 03:01:17 INFO openvpn: starting
2021/07/22 03:01:17 INFO firewall: setting VPN connection through firewall...
2021/07/22 03:01:17 INFO openvpn configurator: starting OpenVPN 2.5
2021/07/22 03:01:17 INFO openvpn: 2021-07-22 03:01:17 DEPRECATED OPTION: ncp-disable. Disabling cipher negotiation is a deprecated debug feature that will be removed in OpenVPN 2.6
2021/07/22 03:01:17 INFO openvpn: OpenVPN 2.5.2 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  4 2021
2021/07/22 03:01:17 INFO openvpn: library versions: OpenSSL 1.1.1k  25 Mar 2021, LZO 2.10
2021/07/22 03:01:17 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]173.208.45.34:443
2021/07/22 03:01:17 INFO openvpn: UDP link local: (not bound)
2021/07/22 03:01:17 INFO openvpn: UDP link remote: [AF_INET]173.208.45.34:443
2021/07/22 03:01:33 INFO healthcheck: program has been unhealthy for 16s: restarting OpenVPN
2021/07/22 03:01:33 INFO openvpn: stopping
2021/07/22 03:01:33 INFO openvpn: starting
2021/07/22 03:01:33 INFO firewall: setting VPN connection through firewall...
2021/07/22 03:01:33 INFO openvpn configurator: starting OpenVPN 2.5
2021/07/22 03:01:33 INFO openvpn: 2021-07-22 03:01:33 DEPRECATED OPTION: ncp-disable. Disabling cipher negotiation is a deprecated debug feature that will be removed in OpenVPN 2.6
2021/07/22 03:01:33 INFO openvpn: OpenVPN 2.5.2 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  4 2021
2021/07/22 03:01:33 INFO openvpn: library versions: OpenSSL 1.1.1k  25 Mar 2021, LZO 2.10
2021/07/22 03:01:33 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]138.186.142.202:443
2021/07/22 03:01:33 INFO openvpn: UDP link local: (not bound)
2021/07/22 03:01:33 INFO openvpn: UDP link remote: [AF_INET]138.186.142.202:443
2021/07/22 03:01:33 WARN openvpn: 'link-mtu' is used inconsistently, local='link-mtu 1601', remote='link-mtu 1550'
2021/07/22 03:01:33 WARN openvpn: 'auth' is used inconsistently, local='auth SHA512', remote='auth [null-digest]'
2021/07/22 03:01:33 WARN openvpn: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo'
2021/07/22 03:01:33 INFO openvpn: [pty-358.windscribe.com] Peer Connection Initiated with [AF_INET]138.186.142.202:443
2021/07/22 03:01:35 ERROR openvpn: AUTH: Received control message: AUTH_FAILED

Your credentials might be wrong 🤨


2021/07/22 03:01:35 INFO openvpn: SIGUSR1[soft,auth-failure] received, process restarting
2021/07/22 03:01:45 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]138.186.142.202:443
2021/07/22 03:01:45 INFO openvpn: UDP link local: (not bound)
2021/07/22 03:01:45 INFO openvpn: UDP link remote: [AF_INET]138.186.142.202:443
2021/07/22 03:01:45 WARN openvpn: 'link-mtu' is used inconsistently, local='link-mtu 1601', remote='link-mtu 1550'
2021/07/22 03:01:45 WARN openvpn: 'auth' is used inconsistently, local='auth SHA512', remote='auth [null-digest]'
2021/07/22 03:01:45 WARN openvpn: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo'
2021/07/22 03:01:45 INFO openvpn: [pty-358.windscribe.com] Peer Connection Initiated with [AF_INET]138.186.142.202:443
2021/07/22 03:01:46 ERROR openvpn: AUTH: Received control message: AUTH_FAILED

Your credentials might be wrong 🤨


2021/07/22 03:01:46 INFO openvpn: SIGUSR1[soft,auth-failure] received, process restarting
2021/07/22 03:01:54 INFO healthcheck: program has been unhealthy for 21s: restarting OpenVPN
2021/07/22 03:01:54 INFO openvpn: stopping
2021/07/22 03:01:54 INFO openvpn: starting
2021/07/22 03:01:54 INFO firewall: setting VPN connection through firewall...
2021/07/22 03:01:54 INFO openvpn configurator: starting OpenVPN 2.5
2021/07/22 03:01:54 INFO openvpn: 2021-07-22 03:01:54 DEPRECATED OPTION: ncp-disable. Disabling cipher negotiation is a deprecated debug feature that will be removed in OpenVPN 2.6
2021/07/22 03:01:54 INFO openvpn: OpenVPN 2.5.2 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  4 2021
2021/07/22 03:01:54 INFO openvpn: library versions: OpenSSL 1.1.1k  25 Mar 2021, LZO 2.10
2021/07/22 03:01:54 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]185.156.174.12:443
2021/07/22 03:01:54 INFO openvpn: UDP link local: (not bound)
2021/07/22 03:01:54 INFO openvpn: UDP link remote: [AF_INET]185.156.174.12:443
2021/07/22 03:02:20 INFO healthcheck: program has been unhealthy for 26s: restarting OpenVPN
2021/07/22 03:02:20 INFO openvpn: stopping
2021/07/22 03:02:20 INFO openvpn: starting
2021/07/22 03:02:20 INFO firewall: setting VPN connection through firewall...
2021/07/22 03:02:20 INFO openvpn configurator: starting OpenVPN 2.5
2021/07/22 03:02:20 INFO openvpn: 2021-07-22 03:02:20 DEPRECATED OPTION: ncp-disable. Disabling cipher negotiation is a deprecated debug feature that will be removed in OpenVPN 2.6
2021/07/22 03:02:20 INFO openvpn: OpenVPN 2.5.2 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  4 2021
2021/07/22 03:02:20 INFO openvpn: library versions: OpenSSL 1.1.1k  25 Mar 2021, LZO 2.10
2021/07/22 03:02:20 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]185.156.175.180:443
2021/07/22 03:02:20 INFO openvpn: UDP link local: (not bound)
2021/07/22 03:02:20 INFO openvpn: UDP link remote: [AF_INET]185.156.175.180:443
2021/07/22 03:02:51 INFO healthcheck: program has been unhealthy for 31s: restarting OpenVPN
2021/07/22 03:02:51 INFO openvpn: stopping
2021/07/22 03:02:51 INFO openvpn: starting
2021/07/22 03:02:51 INFO firewall: setting VPN connection through firewall...
2021/07/22 03:02:51 INFO openvpn configurator: starting OpenVPN 2.5
2021/07/22 03:02:51 INFO openvpn: 2021-07-22 03:02:51 DEPRECATED OPTION: ncp-disable. Disabling cipher negotiation is a deprecated debug feature that will be removed in OpenVPN 2.6
2021/07/22 03:02:51 INFO openvpn: OpenVPN 2.5.2 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  4 2021
2021/07/22 03:02:51 INFO openvpn: library versions: OpenSSL 1.1.1k  25 Mar 2021, LZO 2.10
2021/07/22 03:02:51 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]198.55.126.131:443
2021/07/22 03:02:51 INFO openvpn: UDP link local: (not bound)
2021/07/22 03:02:51 INFO openvpn: UDP link remote: [AF_INET]198.55.126.131:443
2021/07/22 03:02:51 WARN openvpn: 'link-mtu' is used inconsistently, local='link-mtu 1601', remote='link-mtu 1550'
2021/07/22 03:02:51 WARN openvpn: 'auth' is used inconsistently, local='auth SHA512', remote='auth [null-digest]'
2021/07/22 03:02:51 WARN openvpn: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo'
2021/07/22 03:02:51 INFO openvpn: [dfw-86.windscribe.com] Peer Connection Initiated with [AF_INET]198.55.126.131:443
2021/07/22 03:02:53 INFO openvpn: TUN/TAP device tun0 opened
2021/07/22 03:02:53 INFO openvpn: /sbin/ip link set dev tun0 up mtu 1500
2021/07/22 03:02:53 INFO openvpn: /sbin/ip link set dev tun0 up
2021/07/22 03:02:53 INFO openvpn: /sbin/ip addr add dev tun0 10.122.126.20/23
2021/07/22 03:02:53 INFO openvpn: Initialization Sequence Completed
2021/07/22 03:02:53 INFO VPN routing IP address: 198.55.126.131
2021/07/22 03:02:53 INFO dns over tls: downloading DNS over TLS cryptographic files
2021/07/22 03:02:53 INFO healthcheck: healthy!
2021/07/22 03:02:56 INFO dns over tls: downloading hostnames and IP block lists
2021/07/22 03:02:56 INFO dns over tls: init module 0: validator
2021/07/22 03:02:56 INFO dns over tls: init module 1: iterator
2021/07/22 03:02:56 INFO dns over tls: start of service (unbound 1.13.1).
2021/07/22 03:02:56 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN
2021/07/22 03:02:57 INFO dns over tls: ready
2021/07/22 03:02:57 INFO There is a new release v3.20.0 (v3.20.0) created 3 days ago
2021/07/22 03:02:58 INFO ip getter: Public IP address is 198.55.126.139 (United States, Texas, Dallas)
```

**Comment by qdm12** [comment]
🤔 Very strange... I see openvpn:

1. Not doing anything or maybe taking too long: I'll add a default unhealthy timeout env variable so we can test with longer than a few seconds
2. Auth failed twice... not sure why
3. Then working and connecting in 2 seconds, lol

What a strange mess.

What if you try with the same server with the latest image and this one, does it work as well? Maybe these are just some of their servers misbehaving?

**Comment by qdm12** [comment]
You can now configure `HEALTH_OPENVPN_DURATION_INITIAL` and `HEALTH_OPENVPN_DURATION_ADDITION`, maybe try with `HEALTH_OPENVPN_DURATION_INITIAL=1m` to wait one minute before restarting openvpn?

By default it's:

- `HEALTH_OPENVPN_DURATION_INITIAL=6s`
- `HEALTH_OPENVPN_DURATION_ADDITION=5s`

**Comment by TJJP** [comment]
@qdm12 I did some testing and it has seemed to have trouble connecting only after building the docker file, if I run it again without rebuilding it would immediately connect. Later, pulling the latest version and that connected right away (without error). So maybe there is something wacky with how my docker builds gluetun. 

Now testing it more with the latest version, if I do not pull the image first before starting it, it goes into this saying it does not take my credentials, but it eventually connects after 2-3 tries. Setting the `HEALTH_OPENVPN_DURATION_INITIAL=1m` does not seem to fix the issue, takes longer till it retries, but makes it so that it connects. If I delete the downloaded image then start it, it does not have any trouble.

It is probably not worth worrying about because it DOES connect after a few seconds either way. It might be just something with windscribe taking longer to connect. 🤷

**Comment by qdm12** [comment]
Try with the same `SERVER_HOSTNAME` and check the server IP is the same. It might just be one or more of their servers misbehaving (or gluetun has an expired IP address). You can update the server information, see https://github.com/qdm12/gluetun/wiki/Updating-Servers

**Comment by TJJP** [comment]
Yes, I think I found the problem, it appears that some of the `ips` in the `servers.json` are out of date. I noticed that every time gluetun tried to connect to `173.44.36.68` it would fail, but if it would connect to `173.44.36.67` no problem. It would seem that it would depend on the server gluetun happens to pick. that's why it seemed to be so random. I ran the update for the server information, but the `192.44.36.68` is still on the list, so I guess that a lot of dead servers on that list. I don't know how to find, the ips, but I can help if you need.

**Comment by qdm12** [comment]
Servers for Windscribe are fetched from their API at https://github.com/qdm12/gluetun/blob/master/internal/updater/providers/windscribe/api.go#L43 and the IPs are directly from their API.

You can try accessing `https://assets.windscribe.com/serverlist/mob-v2/1/4321423428123` (where `4321423428123` is just a random number to break the cache), and you will see `173.44.36.68` is still there... so that's one them 😄

**Comment by TJJP** [comment]
I found out that reason why 173.44.36.68 does not work. It is a ip3 which is a WG + stealth. I think if the servers.json only got the ip1 and ip2, it would work better. As far as I know, glutun does not support WG + stealth? 
image

**Comment by TJJP** [comment]
I tried to set up the developer environment on my Windows machine, is there a reason why I cannot build the gluetun? 
image

**Comment by TJJP** [comment]
> I tried to set up the developer environment on my Windows machine, is there a reason why I cannot build the gluetun?

I fixed it by removing this line for me. Not sure why it was giving me grief:
https://github.com/qdm12/gluetun/blob/abbcf60aed0c6f9699c0ce4bec5e63e4bcced109/Dockerfile#L160

**Comment by qdm12** [comment]
Hey @TJJP sorry for the delay answering!

1. `I found out that reason why 173.44.36.68 does not work. It is a ip3 which is a WG + stealth.` On it, will remove the ip3!
1. `I tried to set up the developer environment on my Windows machine, is there a reason why I cannot build the gluetun?` I guess because gluetun uses syscall specific to Linux so running it on a Windows host doesn't work sadly. I actually never tried, but there might not be a way around. You can still try [the development container](https://github.com/qdm12/gluetun/tree/master/.devcontainer) that's what I use on my Windows host. And also thanks for trying to fix yourself, the intention is really appreciated 👍
1. `I fixed it by removing this line for me. Not sure why it was giving me grief` Are you sure? Because you were running `go test ./...` on your Windows host, so that shouldn't interfere with a `docker build` right? I'll also check that, maybe that `apk-tools` version (which is a newer security fix) is no longer available since my last commit.

**Comment by qdm12** [comment]
- Regarding 1: Thanks for finding IP3 were for Wireguard, I wasn't aware of this! It should now be fixed with 1f47c161024881be18ce5f15883c223085e58f3f.
- Regarding 3: indeed, I upgraded `apk-tools` to 2.12.7-r0 and it now builds. But yeah it's a line that will make it harder to build in the future unfortunately, I'm waiting for Alpine to fix their image to come with a apk-tools >= 2.12.6 since it's a security vulnerability (and my CI then shouts at me)

**Pull request merged**
