### PR TITLE
feat(openvpn): Add OPENVPN_MTU env to change default tun-mtu

### LINKED ISSUE #2044: allow to change MTU for all VPNs
### What's the feature 🧐

In certain circumstances MTU needs to be smaller as some networks have issues. Wireguard side seems to have now(link below) MTU parameter but not OpenVPN. Can there be a feature that allows setting lower MTU irrespective of if it is Wireguard or OpenVPN.
I resolve OpenVPN MTU limit problem simply executing below after starting the container, however this should be configurable parameter.
docker exec f86573009ed6 /sbin/ip link set dev tun0 up mtu 1300

https://github.com/qdm12/gluetun/issues/1650

### Extra information and references

_No response_

### PR DESCRIPTION
**Pull request by PseudoResonance**
This resolves #2044.

tun-mtu directive will be omitted if OPENVPN_MTU is unset.

Additionally lowers the default AirVPN TunMTU to 1320 to resolve connection issues, such as the following: #1417 #1989

### CODE REVIEW

**Comment by qdm12** [comment]
Does using for example `OPENVPN_MSSFIX=1320` fix it instead?

**Comment by qdm12** [comment]
> Edit: Never mind, it appears to be working again? I'm not sure what changed, but I'll leave it running for a bit and see.

Yes take your time and let's find out.

I was changing your code actually to have a common `VPN_MTU` common for Wireguard and OpenVPN (and remove `WIREGUARD_MTU`), and default it to `1320` for all. However, I was a bit skeptical this would break OpenVPN setups using the default MTU (I think 1500?). It might also be problematic if the MSSFIX option is used (in that case we should default it to 1500 for retro-compatibility???). Anyway a bit messy in the end, so if we can leave it using OPENVPN_MSSFIX that would be great. Maybe something to write into #1113 (add VPN_MTU, remove OPENVPN_MSSFIX+WIREGUARD_MTU)

**Comment by PseudoResonance** [comment]
After around a month, I think it's been working well with just MSSFIX set. It did have issues a few times for some reason, but after it restarted once or twice it worked. I think the behavior was similar with my MTU flag too though.

**Comment by qdm12** [comment]
Let's close this then, thanks!

**Pull request closed without merging**
